# Generated by Django 5.1.3 on 2024-11-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, null=True)),
                ('domain', models.CharField(max_length=250, null=True)),
                ('year_founded', models.FloatField(null=True)),
                ('industry', models.CharField(max_length=500, null=True)),
                ('size_range', models.CharField(max_length=250, null=True)),
                ('locality', models.CharField(max_length=500, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
                ('linkedin_url', models.URLField(null=True)),
                ('current_employee_estimate', models.IntegerField(null=True)),
                ('total_employee_estimate', models.IntegerField(null=True)),
            ],
        ),
    ]
